### Виконав: Овчар Антон, КА-64
# Лабораторна робота №6
## Пошук власних чисел та векторів симетричних матриць
### 0. Умова

$ A = \begin{pmatrix}
6.92 & 1.08 & 0.99 & 1.15 \\
1.08 & 3.50 & 1.30 & 0.16 \\
0.99 & 1.30 & 6.10 & 2.10 \\
1.15 & 0.16 & 2.10 & 5.44
\end{pmatrix}$

Метод: **QR**

In [2]:
import numpy as np

In [4]:
A = np.matrix([[6.92, 1.08, 0.99, 1.15],
               [1.08, 3.50, 1.30, 0.16],
               [0.99, 1.30, 6.10, 2.10],
               [1.15, 0.16, 2.10, 5.44]])
EPS = 10**(-5)

### 1. Розв'язати часткову проблему власних значень: знайти найбільше та найменше власні числа та відповідні їм власні вектори степеневим методом або методом скалярних добутків.

In [5]:
def get_max_eig(A):
    x = np.random.rand(A.shape[1], 1)
    n = 1
    while True:
        ksi = np.dot(A, x)
        v = np.sign(np.float(ksi[0][0]/x[0][0])) * np.linalg.norm(ksi) / np.linalg.norm(x)
        w = ksi / np.linalg.norm(ksi)
        disc = np.dot(A, w) - np.dot(v, w)
        if np.linalg.norm(disc) < EPS:
            break
        x = w
        n += 1
    return v, w, disc, n
        
            
v, w, discrepancy, n = get_max_eig(A)

In [6]:
print('Максимальне власне число\n %s\n' % v)
print('Відповідний власний вектор\n %s\n' % w)
print('Вектор нев\'язки\n %s\n' % discrepancy)
print('Кількість ітерацій\n %s' % n)

Максимальне власне число
 9.378584012942195

Відповідний власний вектор
 [[0.58161346]
 [0.25157177]
 [0.59332306]
 [0.49639215]]

Вектор нев'язки
 [[-7.22308831e-06]
 [-5.30116864e-07]
 [ 4.63659207e-06]
 [ 3.18989057e-06]]

Кількість ітерацій
 22


In [7]:
def get_min_eig(A, v_max):
    B = A - v_max * np.eye(A.shape[0])
    v1, w1, disc, n = get_max_eig(B)
    return v1 + v_max, w1, disc, n

v1, w1, discrepancy1, n1 = get_min_eig(A, v)
print('Мінімальне власне число\n %s\n' % v1)
print('Відповідний власний вектор\n %s\n' % w1)
print('Вектор нев\'язки\n %s\n' % discrepancy)
print('Кількість ітерацій\n %s' % n)

Мінімальне власне число
 2.568232641888657

Відповідний власний вектор
 [[ 0.18902734]
 [-0.79070115]
 [ 0.45449558]
 [-0.36399743]]

Вектор нев'язки
 [[-7.22308831e-06]
 [-5.30116864e-07]
 [ 4.63659207e-06]
 [ 3.18989057e-06]]

Кількість ітерацій
 22


### 2. Розвязати повну проблему методом QR розкладу.

In [31]:
def qr_method(A):
    X = np.copy(A)
    W = np.eye(X.shape[0])
    n = 1
    while True:
        q, r = np.linalg.qr(X)
        Y = np.dot(r, q)
        W = np.dot(W, q)
        disc = np.dot(A, W) - np.dot(X, W.T).T
        print('Ітерація %s' % n)
        print('Похибка - %s' % np.linalg.norm(disc))
        print('Норма Фробініуса - %s' % np.linalg.norm(Y))
        print('Матриця Q\n%s' % q)
        print('Матриця R\n%s\n' % r)
        
        if np.linalg.norm(disc) < EPS:
            return np.array([X[i][i] for i in range(X.shape[0])]), W, disc, n
        n += 1
        X = Y
            
v2, w2, discrepancy2, n2 = qr_method(A)

Ітерація 1
Похибка - 5.918000413853143
Норма Фробініуса - 12.088391125373136
Матриця Q
[[-0.96563508  0.18335401  0.13400323 -0.12638562]
 [-0.15070605 -0.93392565  0.30227371  0.117052  ]
 [-0.13814722 -0.30473111 -0.8846943  -0.3246079 ]
 [-0.16047404  0.0360989  -0.32861791  0.93002969]]
Матриця R
[[-7.16626821 -1.7756243  -2.3315901  -2.29768124]
 [ 0.         -3.46109207 -2.81563499 -0.38212833]
 [ 0.          0.         -5.56111384 -3.44307198]
 [ 0.          0.          0.          4.25106977]]

Ітерація 2
Похибка - 3.898868224198815
Норма Фробініуса - 12.088391125373136
Матриця Q
[[-0.97551886  0.16131812  0.13708722  0.05955256]
 [-0.12034244 -0.93354069  0.30506837 -0.1447507 ]
 [-0.16354069 -0.31209793 -0.90311511  0.24542294]
 [ 0.08446945 -0.07122591  0.26930183  0.95669656]]
Матриця R
[[-8.07613107 -1.68255256 -2.58506452  1.2094409 ]
 [ 0.         -4.14993948 -3.04203356 -0.09891558]
 [ 0.          0.         -5.18113936  2.27964549]
 [ 0.          0.          0.        

In [32]:
print('Власні числа\n %s\n' % v2)
print('Власні вектори\n %s\n' % w2)
print('Вектори нев\'язки\n %s\n' % discrepancy2)
print('Кількість ітерацій\n %s' % n2)

Власні числа
 [9.37858401 5.85618647 4.15699687 2.56823264]

Власні вектори
 [[ 0.58161145 -0.78738601  0.07758798 -0.18902775]
 [ 0.25157162 -0.0586897  -0.55502642  0.79070406]
 [ 0.59332435  0.50481386 -0.43193171 -0.45449332]
 [ 0.49639304  0.3489151   0.70665463  0.36399372]]

Вектори нев'язки
 [[ 9.79485009e-08 -5.65833430e-07  4.96174118e-06  1.85281402e-08]
 [ 7.30207805e-09  3.49804060e-06  5.62088065e-07 -1.32533277e-07]
 [-6.27964596e-08  2.67286414e-06 -3.31851730e-06 -1.03140580e-07]
 [-4.34056115e-08 -4.55523139e-06 -2.13189128e-06  1.68739776e-07]]

Кількість ітерацій
 36


### Перевірка результатів за допомогою сторонніх програмних пакетів

In [33]:
v, w = np.linalg.eig(A)
print('Власні числа\n %s\n' % v)
print('Власні вектори\n %s' % w)

Власні числа
 [9.37858401 5.85618648 2.56823264 4.15699687]

Власні вектори
 [[ 0.58161141  0.78738534 -0.18902775  0.07759518]
 [ 0.25157162  0.0586948   0.79070409 -0.55502584]
 [ 0.59332438 -0.50480987 -0.45449329 -0.43193636]
 [ 0.49639306 -0.34892154  0.36399368  0.70665146]]


### Висновок
В даній лабораторній роботі був реалізований QR метод пошуку власних значень та власних векторів. Були отримані результати з будь-якою наданою точністю, що свідчить про гарну реалізацію методу. Також було застосовано степеневий метод, який підтвердив правильність QR методу